name: Appium CI/CD Test

on: [push, pull_request]

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'
  MAVEN_CACHE: maven

  ANDROID_PROFILE: Nexus 6
  ANDROID_TARGET: google_apis
  ANDROID_API_LEVEL: 28
  ANDROID_ARCH: x86_64

  ARTIFACT_NAME_REMOTE: allure-results-android-remote
  GH_PAGES_URL: https://github.com/zahraamahmoud/E-commerceAppTestByAppium.git

defaults:
  run:
    shell: bash

jobs:
  # --------------------------
  # Android Tests on Emulator
  # --------------------------
  run-android-tests-remote:
    runs-on: ubuntu-latest
    outputs:
      maven_tests: ${{ steps.maven_tests.outcome }}

    steps:
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.MAVEN_CACHE }}

      - name: Build with Maven
        run: mvn install -DskipTests

      - name: Start Appium Server
        run: |
          chmod +x ./ci/prepareAppiumServer.sh
          ./ci/prepareAppiumServer.sh

      - name: Run tests on Android emulators
        id: maven_tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.ANDROID_API_LEVEL }}
          target: ${{ env.ANDROID_TARGET }}
          arch: ${{ env.ANDROID_ARCH }}
          profile: ${{ env.ANDROID_PROFILE }}
          script: |
            adb devices
            chmod +x ./ci/uploadAPK.sh
            ./ci/uploadAPK.sh

            mvn test -Dsurefire.suiteXmlFiles=MobileAutomationSuite.xml \
                     -Dallure.results.directory=target/allure-results || true

            echo "Closing connection with emulator-5554"
            adb -s emulator-5554 emu kill || true

          

      - name: Upload results (emulator)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME_REMOTE }}
          path: ./target/allure-results

      #--------------------------
      # Generate and Publish reports
      # --------------------------
  deploy-report:
    if: always()
    name: Generate and deploy Allure Report
    needs: [ run-android-tests-remote]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout reports branch
        uses: actions/checkout@v4
        with:
          ref: reports
          path: reports
        continue-on-error: true

      - name: Download artifacts - Emulator
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME_REMOTE }}
          path: allure-results

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: reports
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy to GitHub reports
        if: always()
        uses: peaceiris/actions-reports@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: reports
          PUBLISH_DIR: allure-history

      - name: Post reports link
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: 'Test report'
          state: ${{ needs.run-android-tests-remote.outputs.maven_tests == 'success' || 'failure' }}
          sha: ${{ github.event.pull_request.head.sha || github.sha }}
          target_url: ${{ env.GH_PAGES_URL }}/${{ github.run_number }}/